### ISSUE TITLE
Getting 404s against api/v1/dataspaces/%s/ingest

### ISSUE THREAD

**Issue by mlapping** [humio/cloudwatch2humio#14]
https://github.com/humio/cloudwatch2humio/blob/master/lambdas/ingester.py#L53

Is this endpoint legacy? I couldn't find this endpoint in the API docs. In any case, this fails for me in my `HumioCloudwatchIngester` lambda, installed through the [CloudFormation link in the documentation](https://docs.humio.com/integrations/platforms/aws-cloudwatch/#launch)

```
HTTP Error 404: Not Found: HTTPError
Traceback (most recent call last):
  File "/var/task/ingester.py", line 97, in lambda_handler
    f = urllib2.urlopen(request)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

**Comment by Suzanna-Volkov** [comment]
Yes, you are right. The endpoint is legacy. I am working on getting it fixed right now. Thanks for your comment!

**Comment by andejens** [comment]
@mlapping as mentioned by Suzanna we are working on a new and improved version. We expect to release it in the near future.

**Comment by Suzanna-Volkov** [comment]
@mlapping, the integration has now been updated with some new features as well. See the documentation, give it a go, and tell us if anything can be improved. :) I will close this issue as the legacy endpoint has also been updated.
