### ISSUE TITLE
Improving the Update-Stack Flow

### ISSUE THREAD

**Issue by Suzanna-Volkov** [humio/cloudwatch2humio#23]
**What is the issue?**
At the moment, you will have to delete a stack and create a new when you want to update to the newest version of the integration. This is far from ideal as this will introduce a gap in the logs received in Humio between when the integration was deleted to be replaced by a newer version. 

**Proposed solution**
Adding versioning to the ZIPs containing the lambdas hosted and refer to specific versions with a parameter in the CloudFormation file. This will allow users to use the update feature in AWS CloudFormation normally to update the integration without having to delete it as they can choose which version of the lambdas they want to use.

**Comment by Lhusted-code** [comment]
Link to zendesk: https://humio.zendesk.com/agent/tickets/1925

**Comment by Suzanna-Volkov** [comment]
The issue should be solved with the new release. :)

**Comment by camilleacey** [comment]
@Suzanna-Volkov Does this mean this works on 1.14.1 or that it WILL work in 1.15 or??
