### ISSUE TITLE
Back-filler deletes existing subscription

### ISSUE THREAD

**Issue by kbadk** [humio/cloudwatch2humio#31]
When installing cloudwatch2humio, HumioCloudWatchLogsBackfiller deletes existing subscriptions:

https://github.com/humio/cloudwatch2humio/blob/93eb520640ea829f82f631d5900389bdf63654fd/src/logs_backfiller.py#L76-L88

This is not mentioned [in the documentation](https://docs.humio.com/docs/ingesting-data/log-formats/amazon-cloudwatch/#humiocloudwatchlogsbackfiller). According to the documentation, HumioCloudWatchLogsBackfiller innocently subscribes to existing log groups – nothing more:

>This function will paginate through your existing CloudWatch log groups and subscribe the HumioCloudWatchLogsIngester to every single one.

If this really is desired behavior – which I don't think it is – it should be made very clear in the documentation that installing cloudwatch2humio is desctructive to existing infrastructure!

**Comment by squatched** [comment]
This is dangerous and a real problem.

I independently observed this problem in my own analysis of the code for usage and determined that this keeps the backfiller from being usable and I recommend nobody use the backfiller until this is fixed. I understand the intent but the current execution is dangerous.

**Comment by Suzanna-Volkov** [comment]
Thanks for reporting this! I will update the docs for a starter, and then I will take a look into how this can be improved. CloudWatch should support two subscriptions per log group, and that hasn't been taken advantage of. I am thinking that the behaviour should be that the backfiller subscribes and only removes one other subscriptions if that is necessary, but this will be explicitly stated in the docs. However, I will start with updating the docs to reflect the current behaviour and its dangers.

**Comment by kbadk** [comment]
I don't think you should remove any subscriptions, ever. If the backfiller can't subscribe, it should fail. Killing other logging for any reason without explicit permission from the uesr is not acceptable behaviour, in my opinion.

**Comment by Suzanna-Volkov** [comment]
@kbadk yes, thinking about it. I think you are completely right. I will just have to make it clear why the backfiller fails in this case.
