### ISSUE TITLE
S3 Bucket "humio-public" Is Hard-Coded In CFT

### ISSUE THREAD

**Issue by squatched** [humio/cloudwatch2humio#33]
If I'm working on deploying this into our infrastructure, I cannot deploy my own version, I can **only** deploy what is currently in the Humio controlled buckets "humio-public-<region>".

Here's one of the 5 places in cloudformation.json this reference is hard coded.
https://github.com/humio/cloudwatch2humio/blob/93eb520640ea829f82f631d5900389bdf63654fd/cloudformation.json#L179-L181

This should be a parameter that defaults to "humio-public" with instructions in the readme that indicate this bucket must be created in all regions one wishes to deploy with regional names (e.g. - if "my-bucket" is passed in as a CFT parameter and I wish to deploy this in us-west-2 and us-east-1, then the buckets that must be created are "my-bucket-us-west-2" and "my-bucket-us-east-1" in the appropriate regions).

**Comment by Suzanna-Volkov** [comment]
This issue has been solved in the new release.
