### ISSUE TITLE
Merge `cloudformation.json` and `cloudformation-no-trail.json`

### ISSUE THREAD

**Issue by squatched** [humio/cloudwatch2humio#36]
`cloudformation.json` and `cloudformation-no-trail.json` are largely repetitions of each other, the former simply creates some resources that latter does not. Turn the creation of cloudtrail resources into a CFT boolean parameter, then predicate creation of those resources on a conditional that is determined by that parameter.

This will avoid drift between the two files. There already is a little. It's minor right now, but it is likely to grow in the future.

Here's that drift (spelling of the word "lambda"):
https://github.com/humio/cloudwatch2humio/blob/93eb520640ea829f82f631d5900389bdf63654fd/cloudformation.json#L64
https://github.com/humio/cloudwatch2humio/blob/93eb520640ea829f82f631d5900389bdf63654fd/cloudformation-no-trail.json#L64

**Comment by Suzanna-Volkov** [comment]
This issue has been solved with the new release.
