### ISSUE TITLE
Allow configuration of the `#type` to allow explicit Parser association for groups

### ISSUE THREAD

**Issue by jrnt30** [humio/cloudwatch2humio#5]
For our current use case we are evaluating this to ship our CloudTrail logs to Humio.  We created a discrete Log Group, so we have a well known sturcture to the logs. We would like the ability to associate an explicit Parser to take advantage of some of Humio's JSON parser deconstruction by configuring the shipper via a CloudFormation parameter. 

I could see if a user has mixed content in a single log group or has the auto-subscription on without structure logging that this might be a bit less useful.

**Comment by jrnt30** [comment]
Digging a bit deeper I ended up finding the Cloudtrail specific lambda that "Just Worked" after I associated it with the CloudTrail bucket.  

Perhaps a revised request/suggestion would be adding in a bit of conditional logic to the CF template to allow "Log Group" vs. "CloudTrail" sourced data and conditionally activate one or the other of the deployed Lambdas

**Comment by Suzanna-Volkov** [comment]
Cleaning up old issues.
